<?php
// module/Album/view/album/album/delete.phtml:

$title = 'Delete photo';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete '<?php echo $this->escapeHtml($photo->title); ?>'

</p>
<?php
$url = $this->url('album', array(
    'action' => 'deletephoto',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $photo->id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>